repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/crate-ci/typos
    rev: v1.16.2
    hooks:
    -   id: typos
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        args: [--py38-plus]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        args: [ --config, .black ]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
